codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  
ignore:
  - "Attribute.java"
  - "Caretaker.java"
  - "ClassBox.java"
  - "CLIController.java"
  - "CLIView.java"
  - "Driver.java"
  - "Field.java"
  - "GUIController.java"
  - "GUIView.java"
  - "JSON.java"
  - "Memento.java"
  - "Parameter.java"
  - "Relationship.java"
  - "RelLine.java"
  - "UMLClass.java"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

fixes:
  - "::maven/initial"
