codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  
ignore:
  - "uml/Attribute.java"
  - "uml/Caretaker.java"
  - "uml/ClassBox.java"
  - "uml/CLIController.java"
  - "uml/CLIView.java"
  - "uml/Driver.java"
  - "uml/Field.java"
  - "uml/GUIController.java"
  - "uml/GUIView.java"
  - "uml/JSON.java"
  - "uml/Memento.java"
  - "uml/Parameter.java"
  - "uml/Relationship.java"
  - "uml/RelLine.java"
  - "uml/UMLClass.java"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

fixes:
  - "::maven/initial"
