codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  
ignore:
  - ".*/Caretaker.java"
  - ".*/ClassBox.java"
  - ".*/CLIController.java"
  - ".*/CLIView.java"
  - ".*/Driver.java"
  - ".*/GUIController.java"
  - ".*/GUIView.java"
  - ".*/JSON.java"
  - ".*/RelLine.java"
  - ".*/DynamicCompleter.java"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
